# This is a basic workflow to apply Snyk tags to your projects

# The name of the workflow
name: Apply Snyk Tags

# The events that trigger the workflow
on:
  # Trigger the workflow on push or pull request events but only for the master branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Permissions that the workflow has
permissions:
  # The workflow has read permissions for contents
  contents: read

# A workflow run is made up of one or more jobs
jobs:
  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    # Sets up a Python environment with version 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    # Installs the necessary dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    # Runs the tagging script with the necessary environment variables
    - name: Run tagging script
      run: |
        python3 insights/apply-tags.py --org-id ${{env.ORG_ID}} --snyk-token ${{env.SNYK_TOKEN}} --origin github
      env:
        # Snyk token for authentication
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        # Organization ID
        ORG_ID: ${{ secrets.SNYK_ORG_ID }}
