# This workflow is named "Build and Push Docker Image"
name: Build and Push Docker Image

# The workflow is triggered when there is a push to the master branch
on:
    push:
        branches: [ master ]

# The workflow consists of jobs
jobs:

    # This job is named "build"
    build:

        # The job runs on the latest version of Ubuntu
        runs-on: ubuntu-latest

        # The job consists of steps
        steps:
            - uses: actions/checkout@v3
            - name: Docker login
              env:
                DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
              run: docker login -u snykschmidtty -p ${{env.DOCKERHUB_TOKEN}}
            - name: Build the Docker image
              run: DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag snykschmidtty/juice-shop:latest
            - name: Docker Push
              run: docker push snykschmidtty/juice-shop:latest