name: Snyk SBOM Generation

on:
  workflow_dispatch:
  workflow_call:

env:
    ANGULAR_CLI_VERSION: 13
jobs:
  sbom-open-source:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repo
          uses: actions/checkout@master

        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 18.4

        - name: "Install CLI tools"
          run: npm install -g @angular/cli@$ANGULAR_CLI_VERSION

        - name: Install minimalistically
          run: |
            npm install --ignore-scripts
            cd frontend
            npm install --ignore-scripts --legacy-peer-deps

        - name: Setup Snyk
          uses: snyk/actions/setup@master

        - name: Snyk SBOM Generate
          run: snyk sbom --all-projects --exclude=build --format=cyclonedx1.4+json --json-file-output=sbom-cyclonedx.json # Exclude the 'build' directory
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

        - name: Upload SBOM
          uses: actions/upload-artifact@v3
          with:
            name: sbom-cyclonedx
            path: sbom-cyclonedx.json
            retention-days: 5